"""Initial migration or updated schema

Revision ID: d7fca79f09a9
Revises: 
Create Date: 2025-01-15 14:59:43.365718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7fca79f09a9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_collection', schema=None) as batch_op:
        batch_op.add_column(sa.Column('academic_year', sa.String(length=9), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fees_collection', schema=None) as batch_op:
        batch_op.drop_column('academic_year')

    # ### end Alembic commands ###
